services:
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: containers/swagger/Dockerfile
    volumes:
      - ./docs/openapi.yml:/openapi/openapi.yml
    environment:
      - SWAGGER_JSON=/openapi/openapi.yml
    ports:
      - 9000:8080
    networks:
      - rust_back_web
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/rust/Dockerfile
    volumes:
      - ./application:/application
    ports:
      - "8000:8000"
    networks:
      - rust_back_web
    command: /bin/sh -c "cargo watch -x run"
    env_file:
      - .env
networks:
  rust_back_web:
    external: false
