services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - rust_back_db
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: containers/swagger/Dockerfile
    volumes:
      - ./docs/openapi.yml:/openapi/openapi.yml
    environment:
      - SWAGGER_JSON=/openapi/openapi.yml
    ports:
      - 9000:8080
    networks:
      - rust_back_web
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/rust/Dockerfile
    volumes:
      - ./application:/application
    ports:
      - "8000:8000"
    networks:
      - rust_back_web
      - rust_back_db
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "cargo watch -x run"
    env_file:
      - .env
networks:
  rust_back_web:
    external: false
  rust_back_db:
    external: false
volumes:
  db_data:
