[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.8.0"
env_logger = "0.11.3"
futures-util = "0.3.30"
log = "0.4.21"
# common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
