[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
envsubst = "0.2.1"
log = "0.4.21"
once_cell = "1.19.0"
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
